builds:
  - 
    binary: petstore
    main: ./cmd/petstore
    flags: -tags "static_build"
    ldflags: -w -X github.com/prologic/petstore/internal.Version={{.Version}} -X github.com/prologic/petstore/internal.Commit={{.Commit}}
    env:
      - CGO_ENABLED=0
sign:
  artifacts: checksum
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
